dist: xenial

language: python

services:
  - postgresql

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt

env:
  - DJANGO_VERSION=3.0.6

before_script:
  - psql -c 'create database scolendar;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test