version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: scolendar
      POSTGRES_PASSWORD: passwdtest
      POSTGRES_DB: scolendar

  sut:
    build: .
    command: "python manage.py test"
    links:
      - "db:database"
    depends_on:
      - db
