version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: scolendar
      POSTGRES_PASSWORD: passwdtest
      POSTGRES_DB: scolendar

  api:
    build: .
    restart: always
    ports:
      - 3030:3030
    links:
      - "db:database"
    depends_on:
      - db
