version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: scolendar
      POSTGRES_PASSWORD: passwdtest
      POSTGRES_DB: scolendar

  swagger_validator:
    image: swaggerapi/swagger-validator
    restart: always
    ports:
      - 8080:8080

  api:
    build: .
    restart: always
    ports:
      - 3030:3030
    links:
      - "db:database"
      - "swagger_validator"
    depends_on:
      - db
      - swagger_validator
